// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CoverageDataModelAvailable.
const (
	False CoverageDataModelAvailable = false
)

// Valid indicates whether the value is a known member of the CoverageDataModelAvailable enum.
func (e CoverageDataModelAvailable) Valid() bool {
	switch e {
	case False:
		return true
	default:
		return false
	}
}

// Defines values for CoverageDataState.
const (
	Empty     CoverageDataState = "empty"
	Unmodeled CoverageDataState = "unmodeled"
)

// Valid indicates whether the value is a known member of the CoverageDataState enum.
func (e CoverageDataState) Valid() bool {
	switch e {
	case Empty:
		return true
	case Unmodeled:
		return true
	default:
		return false
	}
}

// Defines values for CoverageEnvelopeStatus.
const (
	CoverageEnvelopeStatusSuccess CoverageEnvelopeStatus = "success"
)

// Valid indicates whether the value is a known member of the CoverageEnvelopeStatus enum.
func (e CoverageEnvelopeStatus) Valid() bool {
	switch e {
	case CoverageEnvelopeStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for ErrorEnvelopeStatus.
const (
	Error ErrorEnvelopeStatus = "error"
)

// Valid indicates whether the value is a known member of the ErrorEnvelopeStatus enum.
func (e ErrorEnvelopeStatus) Valid() bool {
	switch e {
	case Error:
		return true
	default:
		return false
	}
}

// Defines values for HealthEnvelopeStatus.
const (
	HealthEnvelopeStatusSuccess HealthEnvelopeStatus = "success"
)

// Valid indicates whether the value is a known member of the HealthEnvelopeStatus enum.
func (e HealthEnvelopeStatus) Valid() bool {
	switch e {
	case HealthEnvelopeStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for SourcesEnvelopeStatus.
const (
	SourcesEnvelopeStatusSuccess SourcesEnvelopeStatus = "success"
)

// Valid indicates whether the value is a known member of the SourcesEnvelopeStatus enum.
func (e SourcesEnvelopeStatus) Valid() bool {
	switch e {
	case SourcesEnvelopeStatusSuccess:
		return true
	default:
		return false
	}
}

// CoverageData defines model for CoverageData.
type CoverageData struct {
	IngestedEvents int64                      `json:"ingested_events"`
	ModelAvailable CoverageDataModelAvailable `json:"model_available"`
	State          CoverageDataState          `json:"state"`
}

// CoverageDataModelAvailable defines model for CoverageData.ModelAvailable.
type CoverageDataModelAvailable bool

// CoverageDataState defines model for CoverageData.State.
type CoverageDataState string

// CoverageEnvelope defines model for CoverageEnvelope.
type CoverageEnvelope struct {
	Data   CoverageData           `json:"data"`
	Error  any                    `json:"error"`
	Meta   any                    `json:"meta"`
	Status CoverageEnvelopeStatus `json:"status"`
}

// CoverageEnvelopeStatus defines model for CoverageEnvelope.Status.
type CoverageEnvelopeStatus string

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Data   any                 `json:"data"`
	Error  string              `json:"error"`
	Meta   any                 `json:"meta"`
	Status ErrorEnvelopeStatus `json:"status"`
}

// ErrorEnvelopeStatus defines model for ErrorEnvelope.Status.
type ErrorEnvelopeStatus string

// HealthData defines model for HealthData.
type HealthData struct {
	Available bool `json:"available"`
}

// HealthEnvelope defines model for HealthEnvelope.
type HealthEnvelope struct {
	Data   HealthData           `json:"data"`
	Error  any                  `json:"error"`
	Meta   any                  `json:"meta"`
	Status HealthEnvelopeStatus `json:"status"`
}

// HealthEnvelopeStatus defines model for HealthEnvelope.Status.
type HealthEnvelopeStatus string

// Page defines model for Page.
type Page struct {
	Limit  int   `json:"limit"`
	Offset int   `json:"offset"`
	Total  int64 `json:"total"`
}

// SourceSummary defines model for SourceSummary.
type SourceSummary struct {
	Id      string `json:"id"`
	License string `json:"license"`
	Name    string `json:"name"`
	Status  string `json:"status"`
	Url     string `json:"url"`
}

// SourcesEnvelope defines model for SourcesEnvelope.
type SourcesEnvelope struct {
	Data   []SourceSummary       `json:"data"`
	Error  any                   `json:"error"`
	Meta   Page                  `json:"meta"`
	Status SourcesEnvelopeStatus `json:"status"`
}

// SourcesEnvelopeStatus defines model for SourcesEnvelope.Status.
type SourcesEnvelopeStatus string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorEnvelope

// RateLimited defines model for RateLimited.
type RateLimited = ErrorEnvelope

// Unavailable defines model for Unavailable.
type Unavailable = ErrorEnvelope

// SourcesParams defines parameters for Sources.
type SourcesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /healthz)
	Health(w http.ResponseWriter, r *http.Request)

	// (GET /readyz)
	Ready(w http.ResponseWriter, r *http.Request)

	// (GET /v1/coverage)
	Coverage(w http.ResponseWriter, r *http.Request)

	// (GET /v1/sources)
	Sources(w http.ResponseWriter, r *http.Request, params SourcesParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /healthz)
func (_ Unimplemented) Health(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /readyz)
func (_ Unimplemented) Ready(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/coverage)
func (_ Unimplemented) Coverage(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/sources)
func (_ Unimplemented) Sources(w http.ResponseWriter, r *http.Request, params SourcesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Ready operation middleware
func (siw *ServerInterfaceWrapper) Ready(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ready(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Coverage operation middleware
func (siw *ServerInterfaceWrapper) Coverage(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Coverage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Sources operation middleware
func (siw *ServerInterfaceWrapper) Sources(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SourcesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Sources(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.Health)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.Ready)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/coverage", wrapper.Coverage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/sources", wrapper.Sources)
	})

	return r
}

type BadRequestJSONResponse ErrorEnvelope

type RateLimitedResponseHeaders struct {
	RetryAfter *int
}
type RateLimitedJSONResponse struct {
	Body ErrorEnvelope

	Headers RateLimitedResponseHeaders
}

type UnavailableJSONResponse ErrorEnvelope

type HealthRequestObject struct {
}

type HealthResponseObject interface {
	VisitHealthResponse(w http.ResponseWriter) error
}

type Health200JSONResponse HealthEnvelope

func (response Health200JSONResponse) VisitHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Health429JSONResponse struct{ RateLimitedJSONResponse }

func (response Health429JSONResponse) VisitHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type Health503JSONResponse struct{ UnavailableJSONResponse }

func (response Health503JSONResponse) VisitHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ReadyRequestObject struct {
}

type ReadyResponseObject interface {
	VisitReadyResponse(w http.ResponseWriter) error
}

type Ready200JSONResponse HealthEnvelope

func (response Ready200JSONResponse) VisitReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Ready429JSONResponse struct{ RateLimitedJSONResponse }

func (response Ready429JSONResponse) VisitReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type Ready503JSONResponse struct{ UnavailableJSONResponse }

func (response Ready503JSONResponse) VisitReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CoverageRequestObject struct {
}

type CoverageResponseObject interface {
	VisitCoverageResponse(w http.ResponseWriter) error
}

type Coverage200JSONResponse CoverageEnvelope

func (response Coverage200JSONResponse) VisitCoverageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Coverage429JSONResponse struct{ RateLimitedJSONResponse }

func (response Coverage429JSONResponse) VisitCoverageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type Coverage503JSONResponse struct{ UnavailableJSONResponse }

func (response Coverage503JSONResponse) VisitCoverageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type SourcesRequestObject struct {
	Params SourcesParams
}

type SourcesResponseObject interface {
	VisitSourcesResponse(w http.ResponseWriter) error
}

type Sources200JSONResponse SourcesEnvelope

func (response Sources200JSONResponse) VisitSourcesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Sources400JSONResponse struct{ BadRequestJSONResponse }

func (response Sources400JSONResponse) VisitSourcesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Sources429JSONResponse struct{ RateLimitedJSONResponse }

func (response Sources429JSONResponse) VisitSourcesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type Sources503JSONResponse struct{ UnavailableJSONResponse }

func (response Sources503JSONResponse) VisitSourcesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /healthz)
	Health(ctx context.Context, request HealthRequestObject) (HealthResponseObject, error)

	// (GET /readyz)
	Ready(ctx context.Context, request ReadyRequestObject) (ReadyResponseObject, error)

	// (GET /v1/coverage)
	Coverage(ctx context.Context, request CoverageRequestObject) (CoverageResponseObject, error)

	// (GET /v1/sources)
	Sources(ctx context.Context, request SourcesRequestObject) (SourcesResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Health operation middleware
func (sh *strictHandler) Health(w http.ResponseWriter, r *http.Request) {
	var request HealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Health(ctx, request.(HealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Health")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthResponseObject); ok {
		if err := validResponse.VisitHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Ready operation middleware
func (sh *strictHandler) Ready(w http.ResponseWriter, r *http.Request) {
	var request ReadyRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Ready(ctx, request.(ReadyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Ready")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReadyResponseObject); ok {
		if err := validResponse.VisitReadyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Coverage operation middleware
func (sh *strictHandler) Coverage(w http.ResponseWriter, r *http.Request) {
	var request CoverageRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Coverage(ctx, request.(CoverageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Coverage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CoverageResponseObject); ok {
		if err := validResponse.VisitCoverageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Sources operation middleware
func (sh *strictHandler) Sources(w http.ResponseWriter, r *http.Request, params SourcesParams) {
	var request SourcesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Sources(ctx, request.(SourcesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Sources")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SourcesResponseObject); ok {
		if err := validResponse.VisitSourcesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFhfb9s2EP8qxG2PXKym6YBpT11aYAH2YKToUxAUZ/Fss6BI9UgJ9QJ994GU/Ee2HNdd4+1NFnV3v/vd",
	"X/oJCldWzpINHvInYPKVs57Sjz9Q3dOXmnyIvwpnA9n0iFVldIFBOzv57J2N73yxpBLj089Mc8jhp8lW",
	"9aQ79ZP3zI7f24aMqwjatpWgyBesq6gMcrizDRqtBPeGWwn3GOgvXepA6nI4eseFiYYFfS2IFCmQsCRU",
	"xImfewq8+uXtPBAPLZfa6rIuIX8lIawqghy0DbQgjqZaCR8tNqgNzgxdzqV3VJFVZAtNXtQ7COKnvZZo",
	"5NY1xLigdxiSUVRKRxVopuwq4qDJQz5H40lCtfPqCbRdkA+kPlGzzqi54xJDx8CvNyC35GSH5EgonSLz",
	"acAO2fj1QzL4uJGZOWcIbZTxAcPul0BlFVYgobZJHSnYyvnA2i6SzzHHNMeseuh1yAMPDhFtVbnZZypS",
	"iq4p29B/Hm0Kw8nwDqLSSqAY7ijUg7G1MYlACjjyOvpX+12SfF0U5P23UVNHJhLMteXe0hgbw0z8Pir2",
	"4O97u4Z6hr+dih/v7Z+EJiy/o1gGSb6f1Xuonk+/DsILJt+Oj//v1Jvi4lz/U4ePDyV+7bt2lslne7gE",
	"N597CoNeP9rOggtozm6Deyx0SmSPdGN8zP8PruaCPtRlibw6t3mr0QIzuiDrafTMYjl+sI35wVHNQ0Jq",
	"1nAqD7SC3lgnv0W1MXWcDf8vC0MHKv2pChkS327AIDOuvqVonlOesvqilRTFtZ27xMNgi5jWM6MLMXe1",
	"VWlNEWRV5bQN/krcutoGLzqJGQmsKnYNKVF1UkyFY+WlsC4INEYUzhjttbP+CiQEHQxBDreOWSvH4u30",
	"DiQ0xL4znl29uspS/VVksdKQw+v0SkKFYZmomSxTs/o7Pi+6Go1RTVjvFOR9twQ5XHavs+yHrWJ7/Xhk",
	"F5uyi3ET2gs0uknRvbn+7ZjiDdLJ7jLcSniTvT4t83Gw60UwEyZUq+MU3cfj/5ahwbaKTCJBvjRPzatJ",
	"0S9eR8lab2YvydfBgjnC2G3NTDb0tWZWgskQ+uiOiFUvNp5cnkTfdeKjHPadOtUxY0khXbEe4o0CcvhS",
	"E6/WEyDfzMEtdYrmWJsA+fUbecYcb+W4gX7AjlrIhgayLDsxyx9fMC32B9zohbq70KxbcBcJ4dOk0uR/",
	"F0yekIulKNAqrTD0BRd7tLaFqVUX/pssO4ZnG/6d/wwumWVxOBI366xJOwZMoH1s/xkA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
